kind: Deployment
apiVersion: apps/v1
metadata:
  name: validation-service
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: validation-service
  template:
    metadata:
      labels:
        app: validation-service
    spec:
      containers:
        - name: validation-service
          image: validationservice
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: validation-service
spec:
  type: LoadBalancer
  ports:
    - name: validation-service
      port: 9000
      targetPort: 80
  selector:
    app: validation-service
